// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatGPT(arg1, arg2) {
  return window['go']['StartWindows']['Api']['ChatGPT'](arg1, arg2);
}

export function Download(arg1, arg2, arg3) {
  return window['go']['StartWindows']['Api']['Download'](arg1, arg2, arg3);
}

export function OpenProject(arg1, arg2) {
  return window['go']['StartWindows']['Api']['OpenProject'](arg1, arg2);
}

export function OpenProjectDialog(arg1, arg2) {
  return window['go']['StartWindows']['Api']['OpenProjectDialog'](arg1, arg2);
}

export function OpenProjectFile(arg1) {
  return window['go']['StartWindows']['Api']['OpenProjectFile'](arg1);
}

export function Ping() {
  return window['go']['StartWindows']['Api']['Ping']();
}

export function Unzip(arg1, arg2, arg3) {
  return window['go']['StartWindows']['Api']['Unzip'](arg1, arg2, arg3);
}

export function UpdateProjectFile(arg1, arg2) {
  return window['go']['StartWindows']['Api']['UpdateProjectFile'](arg1, arg2);
}

export function Xiaomi(arg1, arg2) {
  return window['go']['StartWindows']['Api']['Xiaomi'](arg1, arg2);
}

export function XiaomiAction(arg1, arg2) {
  return window['go']['StartWindows']['Api']['XiaomiAction'](arg1, arg2);
}
