// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {StartWindows} from '../models';

export function ChatGPT(arg1:string,arg2:string):Promise<StartWindows.ChatGPTResponseBody>;

export function Download(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenProject(arg1:string,arg2:string):Promise<string>;

export function OpenProjectDialog(arg1:string,arg2:string):Promise<string>;

export function OpenProjectFile(arg1:string):Promise<string>;

export function Ping():Promise<StartWindows.returnPing>;

export function Unzip(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateProjectFile(arg1:string,arg2:string):Promise<void>;

export function Xiaomi(arg1:string,arg2:string):Promise<any>;

export function XiaomiAction(arg1:string,arg2:string):Promise<any>;
